service: monitoring
provider:
  name: aws
  region: us-east-1
  memorySize: 250
  runtime: python3.9
  timeout: 70
  stage: prod


package:
  exclude:
    - resources/**
    - requests-layer.zip
    - README.md

resources:
  - ${file(resources/roles/lambda_role.yml)}

functions:
  aws_access_list:
    handler: functions/handler.lambda_handler
    events:
      - schedule:
          name: Trigger_aws_access_list_monitoring
          description: 'will trigger the aws bot lambda function every first day of month at 11am UTC'
          rate: cron(0 11 1 * ? *)
    environment:
    #sender and receiver emails must be verified on ses
    # add as many recipients as needed seperated by one space like so RECIPIENT_EMAIL_LIST: 'somemail@gamil.com somemail@gamil.com'
      RECIPIENT_EMAIL_LIST: 'somemail@gamil.com'
      SENDER_EMAIL: 'somemail@gamil.com'
      SES_CONFIGURATION_SET_NAME: 'aws-access-list-monitoring-prod'
    role: AwsAccessListMonitoringLambdaRole
